# Generated by Django 5.2 on 2025-04-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListenSpellWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='The correct word used in Listen & Spell mode', max_length=100)),
                ('audio', models.FileField(blank=True, help_text='Audio file for the word (can be generated via TTS or uploaded manually)', null=True, upload_to='audio/')),
            ],
        ),
    ]
