# Generated by Django 5.2 on 2025-04-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenspellword',
            name='level',
            field=models.CharField(choices=[('Level1', 'Listen & Spell - Word'), ('Level2', 'Sentence Challenge'), ('Level3', 'Paragraph Perfection')], default='Level1', help_text='Choose the difficulty/level of this challenge', max_length=20),
        ),
        migrations.AlterField(
            model_name='listenspellword',
            name='audio',
            field=models.FileField(blank=True, help_text='Audio file generated via TTS or uploaded manually', null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='listenspellword',
            name='text',
            field=models.CharField(help_text='The correct word/sentence/paragraph used in Listen & Spell mode', max_length=100),
        ),
    ]
