# Generated by Django 5.2 on 2025-04-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenge_type',
            field=models.CharField(blank=True, choices=[('Visionary', 'Visionary'), ('Technical', 'Technical'), ('Creative', 'Creative'), ('Leadership', 'Leadership'), ('Strategic Thinking', 'Strategic Thinking'), ('Team Building', 'Team Building'), ('Innovation', 'Innovation'), ('Decision Making', 'Decision Making'), ('Conflict Resolution', 'Conflict Resolution')], max_length=20, null=True),
        ),
    ]
