# Generated by Django 5.2 on 2025-04-12 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_user_points_alter_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='points',
        ),
    ]
