# Generated by Django 5.2 on 2025-04-12 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_remove_user_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborativeStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('user_1_story', models.TextField(blank=True, null=True)),
                ('user_2_story', models.TextField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_1', to='userapp.user')),
                ('user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_2', to='userapp.user')),
            ],
        ),
    ]
