# Generated by Django 5.2 on 2025-04-13 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructorapp', '0001_initial'),
        ('userapp', '0004_collaborativestory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('test_id', models.IntegerField(null=True)),
                ('test_name', models.CharField(max_length=509)),
                ('question', models.CharField(max_length=999)),
                ('useranswer', models.CharField(max_length=999, null=True)),
                ('correctanswer', models.CharField(max_length=999)),
                ('marks', models.IntegerField()),
                ('result_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Student_Result_Details',
            },
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructorapp.addcourse')),
                ('cart_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user')),
            ],
            options={
                'db_table': 'cart_details',
            },
        ),
        migrations.CreateModel(
            name='StudentCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, help_text='Enter fee')),
                ('payment_status', models.CharField(default='pending', max_length=100)),
                ('purchase_date', models.DateField(auto_now_add=True, null=True)),
                ('payment_id', models.CharField(max_length=200)),
                ('order_id', models.CharField(max_length=200)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='instructorapp.addcourse')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_courses', to='userapp.user')),
            ],
            options={
                'db_table': 'student_courses_details',
            },
        ),
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField()),
                ('additional_comments', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user')),
            ],
            options={
                'db_table': 'student_feedback',
            },
        ),
        migrations.CreateModel(
            name='UserTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=155, unique=True)),
                ('test_date', models.DateField(auto_now_add=True)),
                ('test_marks', models.IntegerField(default=0)),
                ('test_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_results', to='userapp.user')),
            ],
            options={
                'db_table': 'User_tests_details',
            },
        ),
    ]
