# Generated by Django 5.2 on 2025-04-13 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_resultmodel_cartmodel_studentcourses_studentfeedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourses',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='studentcourses',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='studentcourses',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='studentcourses',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='studentcourses',
            name='purchase_date',
        ),
    ]
