# Generated by Django 5.2 on 2025-04-13 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_challenge'),
        ('userapp', '0007_leadershipchallenge_leadershipresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.challenge')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers_from_student', to='userapp.user')),
            ],
        ),
        migrations.DeleteModel(
            name='LeadershipChallenge',
        ),
        migrations.DeleteModel(
            name='LeadershipResult',
        ),
    ]
