# Generated by Django 5.2 on 2025-04-13 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_answer_feedback_answer_rating_answer_submission_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.CharField(choices=[('Level1', 'Listen & Spell - Word'), ('Level2', 'Sentence Challenge'), ('Level3', 'Paragraph Perfection')], default='Level1', max_length=20)),
                ('incorrect_attempts', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.user')),
            ],
        ),
    ]
