# Generated by Django 5.2 on 2025-04-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_gameprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprogress',
            name='current_question',
            field=models.IntegerField(default=0),
        ),
    ]
