# Generated by Django 5.2 on 2025-04-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_challenge_challenge_type'),
        ('userapp', '0011_gameprogress_current_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprogress',
            name='completed_challenges',
            field=models.ManyToManyField(blank=True, to='adminapp.listenspellword'),
        ),
    ]
