# Generated by Django 5.2 on 2025-04-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_gameprogress_completed_challenges'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Points'),
        ),
    ]
