# Generated by Django 5.2 on 2025-04-13 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addcourse',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('course_image', models.ImageField(upload_to='course_images/')),
                ('course_category', models.CharField(max_length=100)),
                ('course_language', models.CharField(max_length=100)),
                ('course_description', models.TextField()),
                ('video_url', models.URLField()),
                ('duration_weeks', models.IntegerField()),
                ('price', models.IntegerField(default=0, help_text='Enter fee ')),
                ('added_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Courses_details',
            },
        ),
        migrations.CreateModel(
            name='InstructorRegModel',
            fields=[
                ('instructor_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=55)),
                ('email', models.EmailField(help_text='Enter Email', max_length=100)),
                ('phone_number', models.BigIntegerField(null=True)),
                ('gender', models.CharField(default=False, max_length=50)),
                ('password', models.CharField(help_text='Enter Password', max_length=100)),
                ('photo', models.ImageField(default=False, upload_to='')),
                ('status', models.CharField(default='Pending', max_length=100, null=True)),
                ('reg_date', models.DateField(auto_now_add=True, null=True)),
                ('address', models.CharField(max_length=255)),
                ('otp', models.CharField(default=0, max_length=6)),
                ('otp_status', models.CharField(default='Not Verified', max_length=15)),
            ],
            options={
                'db_table': 'Instructor_Details',
            },
        ),
        migrations.CreateModel(
            name='ImageQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_questions/')),
                ('correct_answer', models.TextField()),
                ('question_type', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10, null=True)),
                ('question_method', models.CharField(default='image', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructorapp.addcourse')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructorapp.instructorregmodel')),
            ],
            options={
                'db_table': 'ImageQuestions',
            },
        ),
        migrations.CreateModel(
            name='DescriptiveQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('correct_answer', models.TextField()),
                ('question_type', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10, null=True)),
                ('question_method', models.CharField(default='descriptive', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructorapp.addcourse')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructorapp.instructorregmodel')),
            ],
            options={
                'db_table': 'DescriptiveQuestions',
            },
        ),
        migrations.AddField(
            model_name='addcourse',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructorapp.instructorregmodel'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10, null=True)),
                ('question_method', models.CharField(default='mcqs', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructorapp.addcourse')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructorapp.instructorregmodel')),
            ],
            options={
                'db_table': 'Questions',
            },
        ),
    ]
