# Generated by Django 5.2 on 2025-04-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcourse',
            name='course_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addcourse',
            name='duration_weeks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addcourse',
            name='price',
            field=models.IntegerField(blank=True, default=0, help_text='Enter fee ', null=True),
        ),
        migrations.AlterField(
            model_name='addcourse',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
